server:
  port: 2003
spring:
  application:
    name: eureka-consumer-ribbon
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka
    fetch-registry: true
    register-with-eureka: true