server:
  port: 2011
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: eureka-client
