server:
  port: 2002
spring:
  application:
    name: eureka-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka
    fetch-registry: true
    register-with-eureka: true